object Versions {
    const val kotlin = "1.7.0"
    const val gradle = "7.2.2"
    const val junit5Gradle = "1.8.2.1"
    const val junit5 = "5.9.0"
    const val kover = "0.5.1"
    const val detekt = "1.21.0"
    const val coroutines = "1.6.4"
    const val ktx = "1.8.0"
    const val ktxLifecycle = "2.5.1"
    const val ktxFragment = "1.5.2"
    const val androidXJunit = "1.1.3"
    const val espresso = "3.4.0"
    const val appCompat = "1.5.0"
    const val material = "1.6.1"
    const val ktlint = "10.3.0"
    const val dagger = "2.43.2"
    const val nav = "2.5.1"
    const val composeCompiler = "1.2.0"
    const val compose = "1.2.1"
    const val composeConstraint = "1.0.1"
    const val composeActivity = "1.5.1"
}